### ISSUE TITLE
.toJS is not a function

### ISSUE THREAD

**Issue by davidfurlong** [auru/redux-sentry#21]
I'm guessing you need to add a peer dependency of `immutable-js`. I see the docs mention it briefly, but I think it should be in the package.json

**Comment by evilj0e** [comment]
Hello, David.
I think it's not necessary. For now you should just overload [transform object](https://github.com/auru/redux-sentry#transform-object-optional) which you pass while middleware creation.

**Comment by Patrickgao91** [comment]
@evilj0e  Hi, I try to overload transform object like this:
` const sentryMiddleware = createSentryMiddleware({ dsn: 'https://dsnURL', transform: {} })`
but the error ".toJS is not a function" still exists, what is the correct structure ?

**Comment by evilj0e** [comment]
@Patrickgao91, hi!

You should override stateTransform value like this:
```
const sentryMiddleware = createSentryMiddleware({
    dsn: 'https://dsnURL',
    transform: {
        stateTransform: a => a
    }
})
```

**Comment by Patrickgao91** [comment]
@evilj0e Thank you!  But it seems that the two fields "dsn" and "transform" can not be included in the same object, I tried this:
`const sentryMiddleware = createSentryMiddleware(
  { dsn: 'https://dsnURL' }, {
    stateTransform: a => a
  })`
Then it works well

**Comment by evilj0e** [comment]
Yes, you're right. It's my fault. Great that I could help you!
