### ISSUE TITLE
Can I remove webpack-sentry-plugin after using redux-sentry?

### ISSUE THREAD

**Issue by Patrickgao91** [auru/redux-sentry#24]
Hi, @evilj0e , our application is a typical React + Redux application, can I remove webpack-sentry-plugin? Or is it nessesary for both of them to exsit in the same project ?

**Comment by evilj0e** [comment]
Hi! redux-senty is independent module. You can remove webpack-sentry-plugin and use only redux-sentry in your project.

**Comment by Patrickgao91** [comment]
OK, thanks
