### ISSUE TITLE
Question : is it possible to easily configure the middleware to only send to sentry when running react in production ?

### ISSUE THREAD

**Issue by aymericbouzy** [auru/redux-sentry#5]
I don't want to log all my blunders during development ...

**Comment by TimeRaider** [comment]
@aymericbouzy do not pass sentry middleware to `applyMiddleware` when setting your store up if `ENV !== 'production'`

**Comment by aymericbouzy** [comment]
That was my initial idea. I end up with the following code:
```js
var store = createStore(reducer, applyMiddleware(...([ENV === 'production' && sentryMiddleware].filter(Boolean))))
```
which looks over complicated to me for such a universal use case. But maybe there isn't a better solution.

**Comment by evilj0e** [comment]
@aymericbouzy, i think in dev and testing mode your domain name differs from production. That's why you also can configurate whitelist of domains from which sentry will store logs.

**Comment by aymericbouzy** [comment]
that seems to be a better solution. I'm new to Sentry, but I think I'm going to love it :) I'll look into that. Thanks!
PS: Obviously this is not the purpose of this repository, but including steps to setup those environments in the readme would have greatly helped me getting started
